name: actions example

on: [push, pull_request]

jobs:
  build:
    name: Testing out Github actions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8]
    steps:
    - name: Set up Python ${{ matrix.python-version }}
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        echo "This is a quick take on actions"
        sudo apt-get update -y && sudo apt-get upgrade -y
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
